### ISSUE TITLE
The platform is not handling correctly the valid collection attached

### ISSUE THREAD

**Issue by lucamaf** [microcks/microcks#10]
the layout of text is a little bit messed up and the endpoint are not correctly filled in
![screenshot from 2017-12-15 15-22-39](https://user-images.githubusercontent.com/1726883/34046035-d14b6f0c-e1ab-11e7-8ad4-d08e44d6bb79.png)
collection here https://raw.githubusercontent.com/lucamaf/workshop/master/dbapi.postman_collection.json

**Comment by lbroudoux** [comment]
Hi Luca, 
2 reasons for bad handling and display of collection.

Easier first: the display is not correct because of CSS style properties missing. I've added them, see result in capture below.

Then, correct handling: the collection you provided is flat. Microcks relies on collection structure to deduce operation names. Just reorganise your query in 2 folders named "v1" and "v2" like I did here (https://raw.githubusercontent.com/microcks/microcks/master/src/test/resources/io/github/microcks/util/postman/DBAPI.reorganised.postman_collection.json) and Microcks will be able to discover correct operations and produce corresponding mocks. URL of mocks are now also displayed within GUI like in the screenshot below.

<img width="1157" alt="capture d ecran 2018-01-05 a 12 37 02" src="https://user-images.githubusercontent.com/1538635/34607887-f72031a2-f215-11e7-97d4-8e2676566c2c.png">

What do you think ? Is that ok for you ?

Best,
