### ISSUE TITLE
UI Validation/Messaging:  Indicate unsupported OpenAPI specification version

### ISSUE THREAD

**Issue by mhockelberg** [microcks/microcks#107]
Regarding https://github.com/microcks/microcks/issues/103 and https://github.com/microcks/microcks/issues/106 and potentially other issues reported...

Since OpenAPI 3 is supported, but OpenAPI 2 is not...

Indicate to the user via the UI during the import task that they are attempting to import a version of the specification that is unsupported.

**Comment by lbroudoux** [comment]
Hi,

sorry for long time since this issue was opened but finally find the time to tackle this ;-) 
I've made some improvements to the error handling and add more log messages to see what's going on when importing a file. Here's also a screenshot of the display in GUI. 

<img width="514" alt="Capture d’écran 2020-02-17 à 17 59 23" src="https://user-images.githubusercontent.com/1538635/74674094-ea95c800-51b0-11ea-8bb4-dea2db16f6c8.png">


Hope it helps ;-)

**Comment by lbroudoux** [comment]
Done and available on the `0.9.0` branch and on the `nightly` container image tag.
