### ISSUE TITLE
Templating rest mock responses' headers

### ISSUE THREAD

**Issue by Afanas10101111** [microcks/microcks#1097]
### Reason/Context

It is not possible to template a response header, but there are scenarios where this is necessary. For example, some service is waiting for a random UUID in some `x-correlation-id`.

### Description

I assume, it would be a good idea to use the already existing templating mechanism and build constructs like
```
      responses:
        "200":
          headers:
            x-some-generic-header:
              schema:
                type: string
              examples:
                generic:
                  value: '{{ randomUUID() }}'
```

### Implementation ideas

The <a href="https://github.com/microcks/microcks/pull/1098">idea</a> is to reuse the already existing templating mechanism.

**Comment by lbroudoux** [comment]
This is a nice idea! Thanks!

**Comment by lbroudoux** [comment]
I've refactored a bit and move most of the code to `MockControllerCommons` so that way we'll be able to reuse it for some other protocols.

Also, I've added request based evaluation, that means that you can also have some header definitions like:

```yaml
x-request-based-header:
  schema:
    type: string
  examples:
    pastries_json:
      value: '{{ request.params[size] }} size'
```

and then receive `x-request-based-header: 'XL size'` when you request `/pastries?size=XL` for example 😉

**Comment by lbroudoux** [comment]
Thanks a lot for this contribution!
