### ISSUE TITLE
Customize the port / hostname for each mock

### ISSUE THREAD

**Issue by nmasse-itix** [microcks/microcks#111]
Currently each mock is deployed on the same port, same hostname and with a path prefix `/rest/{service}/{version}`. 

In order to ease the use of those mocks with client implementations that do not take into account path prefix, it would help to define per mock either a custom port (with only one mock per port) or a hostname (with only one mock per hostname). 

Microcks would then route the request using the hostname or path prefix on the general port 8080 or skip the routing part for custom ports. 

Note: custom ports might be subject to filtering in some companies, so hostname might be better.

**Comment by lbroudoux** [comment]
Hum ... This may me think of being concerns that are more adapted to a proxy component that customer may choose to deploy in front of Microcks ... what do you think ?

Microcks deployment model is precisely to be able to provide dynamic endpoints for any new service ... however this feature will surely require network configuration and redeployment into a container world. Maybe this kind of feature could be achieve with some fancy service mesh hot reconfiguration stuffs ...

It seems a much much more harder path to me than just applying best practices about application configuration and variable externalisation => making your application totally configurable regarding their dependency ! So that they can just use Microcks even without knowing it.

My 2 cents ;-)

**Comment by nmasse-itix** [comment]
> applying best practices about application configuration and variable externalisation => making your application totally configurable regarding their dependencies !

Totally agree that this should be the goal for every development. 

> Microcks deployment model is precisely to be able to provide dynamic endpoints for any new service ... however this feature will surely require network configuration and redeployment into a container world. Maybe this kind of feature could be achieve with some fancy service mesh hot reconfiguration stuffs ...

In OpenShift we have everything we need to accomplish this (wildcard routes) but it may be harder on other platforms.

**Comment by ghostsquad** [comment]
I think this could be easily solved with a proxy like Caddy
https://caddyserver.com/docs/rewrite

**Comment by lbroudoux** [comment]
Marking this issue as `status/invalid` as I think this is not the scope of Microcks to provide specific and customizable routing for published mocks.

We provide default URLs and if custom routes are needed, one should deploy a proxy (like Nginx, Treafik or what else) to map the default routing schema with specific ones.

Do not hesitate commenting and arguing if you think this point deserves more discussions. Always happy to write good arguments to change my mind ;-)
