### ISSUE TITLE
Not creating virtualized endpoints upon successful upload of OpenAPI spec

### ISSUE THREAD

**Issue by mhockelberg** [microcks/microcks#118]
When I upload an OpenAPI spec (v3), the upload is successful.  The API is shown, but no mock endpoints are generated.  Mocks section of the API display are missing.

**Comment by mhockelberg** [comment]
![image](https://user-images.githubusercontent.com/686612/52060820-07764380-253b-11e9-9d20-5b4790445fa9.png)


[employee-service-latest-OpenApi3Json.json.zip](https://github.com/microcks/microcks/files/2817618/employee-service-latest-OpenApi3Json.json.zip)

**Comment by lbroudoux** [comment]
Hi @mhockelberg 

Thanks for trying out Microcks. The result you get is totally normal because you have no example definition within your specification file.

Mocking in Microcks is based on examples provided during design phase. We've make the choice not to generate random request and responses as we think it is of great importance that mocks represent real life use-cases and scenarios. Examples can be embedded into OpenAPI spec or externalized into a Postman Collection. You may have a look at https://microcks.github.io/using/openapi/ that explains how to describe example for OpenAPI. 

I also recommend having a look at Apicurio studio that rocks for API specification edition.

Cheers,
