### ISSUE TITLE
BeerCatalogAPI-swagger not seem to work

### ISSUE THREAD

**Issue by davidamir10** [microcks/microcks#1242]
### Describe the bug

Hello,
I've imported the [BeerCatalogAPI](https://github.com/microcks/microcks/blob/master/samples/BeerCatalogAPI-swagger.json) swagger, import seems to work, however, the operation's GET /beer/findByStatus/{status} mocks are empty, although there are examples in the swagger.
Am I missing something?

### Expected behavior

Mock filled with the examples from the swagger

### Actual behavior

Mocks are empty

### How to Reproduce?

Upload [BeerCatalogAPI](https://github.com/microcks/microcks/blob/master/samples/BeerCatalogAPI-swagger.json) swagger, view operation `GET /beer/findByStatus/{status}`, mock is empty

### Microcks version or git rev

Version 1.9.1-fix-1

### Install method (`docker-compose`, `helm chart`, `operator`, `docker-desktop extension`,...)

docker

**Comment by lbroudoux** [comment]
Hello @davidamir10 ,

This is expected behavior as a Swagger alone is not sufficient to define full mocks. As explained in [Swagger conventions](https://microcks.io/documentation/references/artifacts/swagger-conventions/) you'll also need a companion Postman Collection to hold the mock data set. It is provided in [BeerCatalogAPI-collection.json](https://github.com/microcks/microcks/blob/master/samples/BeerCatalogAPI-collection.json) and must be imported as a secondary artifact. This collection will provide the different examples loaded into the mock.

Let me know if it fixes the situation.

**Comment by davidamir10** [comment]
Thanks @lbroudoux for quick response and explanation.
It's working as expected, I missed that.
Issue can be closed.
