### ISSUE TITLE
Swagger "sample apis" aren't importing sample responses

### ISSUE THREAD

**Issue by Loriden** [microcks/microcks#1332]
### Describe the bug

I encountered some issues importing a swagger spec from our existing API and as we have only just started i used the samples provided in github.com/microcks/microcks/samples to perform isolation testing. I've discovered that all the sample swagger APIs will not import the sample responses, and no error is thrown (at DEBUG log level) in the microcks application or MongoDB. 

### Expected behavior

Importing a swagger API json/yml file with responses should load sample responses for the API to serve. 

### Actual behavior

No samples are shown in microcks or served via the API. 

### How to Reproduce?

1. Use the provided docker or podman compose files to create a 4-container microcks cluster. 
2. Load either BeerCatalogAPI-swagger.json, PetstoreAPI-swagger.json or HelloAPI-swagger.json via the "Importers" tab and the "Direct upload artifact" interface - leave secondary artifact unchecked. 
3. Review uploaded APIs in the "APIs | Services" section, and notice none of the endpoints have samples attached. 
3a. Use curl to view the GET endpoints and receive no response (endpoints are not provided in UI)
3b. Use the contract link in Services > API to view hte imported JSON, and note that there are entries under the  "examples" header that are not being provide

### Microcks version or git rev

1.10, 1.9

### Install method (`docker-compose`, `helm chart`, `operator`, `docker-desktop extension`,...)

docker-compose

### Additional information

Moved away from my organisations OpenAPI spec as i couldn't trust that they would import nicely, due to coming from Mulesoft's RAML and being exported as OAS (openAPI) even for swagger endpoints. Once i could demonstrate with sample data i figured this is either an issue with Microcks and swagger, or the sample files provided by microcks.

**Comment by lbroudoux** [comment]
Hey @Loriden ,

This is totally expected behavior. In fact, Swagger v2 is an incomplete spec that doesn't allow specific examples for request-related parts. So once imported into Microcks, it doesn't allow you to have a comprehensive mock definition. Only the operations and schema information are actually used to get the shape of your API structure.

When using Swagger, you need to complement it with additional secondary artifacts that will hold your examples. See https://microcks.io/documentation/explanations/multi-artifacts/#usage-for-different-protocols 
Typically, you can use either Postman Collection, or APIExamples or HTTP Archive files.

Hope it helps,

**Comment by Loriden** [comment]
Hey Laurent 

Thanks for the response - much appreciated. Apologies for the misunderstanding.
