### ISSUE TITLE
New operations are not getting added when importing updated OpenAPI specification file

### ISSUE THREAD

**Issue by Harsh4902** [microcks/microcks#1376]
### Describe the bug

I was trying to learn about OpenAPI specifacation and trying to generate mocks using it. When I tried to upload updated OpenAPI spec, it's not reflected in existing APIs. 

### Expected behavior

If we upload an updated OpenAPI file with new endpoints or operations, it should be updated with exiting APIs if it's present.

### Actual behavior

Currenlty it's not adding new operations, which are added in updated OpenAPI file to an existing API.

### How to Reproduce?

1. Create an OpenAPI specification with one path and its examples and import.
2. Try to add one more path to that file and try to import the updated file

Bug video: 
https://github.com/user-attachments/assets/29f484c1-50a6-4bea-9085-a56523719821

### Microcks version or git rev

1.10.0

### Install method (`docker-compose`, `helm chart`, `operator`, `docker-desktop extension`,...)

docker images

**Comment by Harsh4902** [comment]
@lbroudoux can you please confirm this issue?

**Comment by lbroudoux** [comment]
Ok got it ;-)

You're encountering this issue because you're ticking the "Secondary artifact" box on the second import. You shouldn't do that because it's basically the same artifact you want to overwrite. Because you tell Microcks to consider it as a secondary, it detects a name conflict with the primary and do not override it. Just re-upload without checking the box and it will be alright.

**Comment by Harsh4902** [comment]
Aha, got your point.
