### ISSUE TITLE
Import file detected as a HAR instead of OpenAPI v3

### ISSUE THREAD

**Issue by lalithaawgu** [microcks/microcks#1395]
### Describe the bug

When importing https://raw.githubusercontent.com/twilio/twilio-oai/main/spec/json/twilio_api_v2010.json for mocks, I see this error HAR version is not supported. Currently supporting: [1.1, 1.2]
Apicurio is able to import it fine however. 

### Expected behavior

The API should have been imported and service created.

### Actual behavior

Import fails.

### How to Reproduce?

Import https://raw.githubusercontent.com/twilio/twilio-oai/main/spec/json/twilio_api_v2010.json.

### Microcks version or git rev

quay.io/microcks/microcks-uber:latest-native 

### Install method (`docker-compose`, `helm chart`, `operator`, `docker-desktop extension`,...)

docker run

**Comment by lbroudoux** [comment]
The fix should be available in the `nightly` tagged container image in a few minutes. Thanks for the feedback once tested.

**Comment by lalithaawgu** [comment]
Thanks, the import succeeds, however the examples do not show up as mocks. Is that expected ?

<img width="1781" alt="image" src="https://github.com/user-attachments/assets/c85135aa-bc09-4677-b05f-9c4c5c96704d">

APICURIO STUDIO:
<img width="754" alt="image" src="https://github.com/user-attachments/assets/6671a0d3-8add-460d-a725-cf8e91ec4bb4">

**Comment by lbroudoux** [comment]
Having a quick look at the Twilio spec, it is expected as it doesn't comply with our [OpenAPI conventions](https://microcks.io/documentation/references/artifacts/openapi-conventions/#conventions) to be able to associate request and response examples fragments and identify comprehensive mocks. This is the difference with Apicurio, who just cares about the example fragments and doesn't try to combine them together. 

If you want to analyze an existing spec and see if Microcks can use its examples, you can look at our [Spectral Ruleset](https://github.com/microcks/microcks-spectral-ruleset).

As import is now ok—even if the result is not what you expect due to the spec—I will close this issue. Do not hesitate to follow up by asking questions or for support via GitHub discussion or Discord! Looking forward to getting news about your experience there!

**Comment by lalithaawgu** [comment]
Awesome! Thanks for the details.
