### ISSUE TITLE
Ask: 404 not found Mock SoapUI

### ISSUE THREAD

**Issue by luisQAsis** [microcks/microcks#150]
Hi,

first of all -thanks for this great project.
I started to play with it just recently so I'm not an experienced user.

i did differents project with SoapUI and i follow all intruction about good practices how names of Mocks,testSuites and request-responses, but when i try up my project in microcks i have problem with de endpoint that generate microcks, when i try use my mock 

[soap project.zip](https://github.com/microcks/microcks/files/3193533/soap.project.zip)

service i dont found it (404), with postman i dont have this problems, only with SoapUI' projects, 

attach my project
sorry but i new with this.

**Comment by lbroudoux** [comment]
Hi @luisQAsis ,

sorry for delay in response ....

Seems like this problem is due to some missing stuffs into your WSDL contract. During the import SoapUI is not able to retrieve the input and output names for operations, that is that informations that are used by Microcks mocks to guess what operation you're invoking.

Here's attached a fixed WSDL with a working SoapUI project.

Thanks for using Microcks !!

Cheers,
[WebServices6.0_ValidatorWS.zip](https://github.com/microcks/microcks/files/3247725/WebServices6.0_ValidatorWS.zip)

**Comment by luisQAsis** [comment]
@lbroudoux  thank you very much!!! you are awesome!! i have another question, how do you expose the contract WSDL in Microcks?   i imagine that Microcks read some tag in the project or in WSDL for expose it

thank you for all.

**Comment by lbroudoux** [comment]
Right. We extract the WSDL from the SoapUI project that embeds it.
