### ISSUE TITLE
Headers Dispatching Rules

### ISSUE THREAD

**Issue by mjaeggi** [microcks/microcks#164]
First of all sorry if this is not the correct place to create this question but I couldn't find a better place. 

Question: There is a way to configure a dispatching rule from a header value?. 
I know that I can configure the constraints but can I choose from one response or another from a header value?

**Comment by lbroudoux** [comment]
Hi @mjaeggi and thanks for your question. We also have a Gitter IM room for quick chatting too: https://gitter.im/microcks/microcks

Unfortunately we do not have yet a mean to dispatch using header value. This is not implemented yet but should be on our plan to have a full OpenAPI / Swagger support for REST APIs. What kind of contract artifact do you use for illustrating such dispatching rules ? Knowing this could help us prioritize stuffs.

Thanks,

**Comment by mjaeggi** [comment]
Hey @lbroudoux, all our API's require the Auth token as the Authorization header and internally we identify the user using the token in a centralized service. The response may change depending on the user that is sending the request. 

I will use `gitter` the next time.
Thanks!

**Comment by lbroudoux** [comment]
Hi,

I understand that the Authorization header is mandatory in your case and as you may have guess this can be checked using constraint on header. But is this the sole parameter that made the response change ?

If true, then you’re right : we’ll need to add dispatch rules based on header value. However I doubt mocks to be usable in real life scenario because usually you cannot predict header value (think of JWT token). 

If false, then header presence is just a constraint and you may have some other changing parts in URL path or as query parameters. This case are handled well today. 

Cheers,

**Comment by mjaeggi** [comment]
Hi, 
It's true. Depending only on the token the response may change. 
Regarding the usability of the mocks, I was thinking on mocking the service that generates the tokens (only for testing purposes) in that way I can control which tokens are "generated"

**Comment by lbroudoux** [comment]
Hi,

That sounds reasonable. Let me know on how you’re getting forward on this.

**Comment by lbroudoux** [comment]
Closing this thread due to inactvity

**Comment by imod** [comment]
I kind of expect that headers defined in a postman collection would be used by microcks to match the incoming request to examples  out of the box. Unfortunate this seems still not to be the case :(
