### ISSUE TITLE
Plans for Microcks on AWS Marketplace

### ISSUE THREAD

**Issue by lbroudoux** [microcks/microcks#232]
We're in the process of thinking about a service offer of Microcks via AWS Marketplace.

Please let us know in comments what you'd like too see:
* Raw Microcks on EC2 ? 
* Microcks as a Service on EKS or ECS ?

**Comment by yrsurya** [comment]
EKS

**Comment by FilipShavash** [comment]
Hi Laurent. I tried to set up Microcks on EC2 based on the available helps but the further i went is the moment that all 4 docker compose starts up ( in fact keycloak does not but after removal of images and rerun docker compose all of them starts up - solution from issue https://github.com/microcks/microcks/issues/354) but the microcks webpage is just blank. There is no issue when i set up everything localy where all the URL point to localhost but on EC2 and with changes on docker-compose.yml URLs things getting bad.

Very old issue 29 explain a bit which URLs has to be changed https://github.com/microcks/microcks/issues/29 but since microcks.yml is not distributed anymore with the latest package it is kind of unknown for me which envoironment variables should point to the public DNS on EC2.

Would you give me some hints which one should be updated to make it work?
a) KEYCLOAK_URL
b) KEYCLOAK_PUBLIC_URL
c) KEYCLOAK_FRONTEND_URL

**Comment by lbroudoux** [comment]
Hi @FilipShavash 

Sorry for inconvenience but things have moved a bit on Keycloak configuration in order to find the easiest and flexible configuration options ...

When looking at the current `docker-compose.yml` file - and in regards of EC2 install - you'll have the following property to set up:
* `KEYCLOAK_URL` is used on the microcks container side and it's the URL used for reaching Keycloak container. So if running on same host with docker-compose, you should stick with `http://keycloak:8080/auth` that is using the docker network local alias,
* `KEYCLOAK_PUBLIC_URL` is used on the microcks container side an it's the public URL that is used in browser for OpenID authentication flow. So it should be something like `http://<my_ec2_publis_dns>:18080/auth` because Keycloak container is exposed on port `18080` of the host,
* `KEYCLOAK_FRONTEND_URL` is used on the keycloak container side to tell it the public URL used to first do the OpenID authentication. So its value must also be set to `http://<my_ec2_publis_dns>:18080/auth` for same reason.

Hope it helps!

**Comment by FilipShavash** [comment]
Hi @lbroudoux 

Many thanks. Tried that one but unfortunetly my EC2 micro becomes irresponsive  When trying to open microcks webpage after all the changes and spin up docker compose it simply goes in endless loop of waiting. there is some time before it all slow down so i can do some screenshots.

Server becomes very slow, so slow that i have to spend couple of minutes to get answer on simple command "ls".

Seems that this machine is not capable to handle the whole project or something else...... Any hints more than welcome.

Or maybe you already tried to fire up that project on some EC2 machine and have some recomendation? 

Below some screenshots from docker-compose.yml and running images before i started to open web access. I am restarting that machine quite offten so public DNS is not permanent over the time - if you would be checking that one.

![image](https://user-images.githubusercontent.com/45749969/129173074-4f57bc58-248c-4030-9435-6011f3679435.png)
![image](https://user-images.githubusercontent.com/45749969/129173103-f0d4f636-c214-4c50-94b7-78bd4c3966a0.png)
![image](https://user-images.githubusercontent.com/45749969/129173114-7c44b700-de3c-4a5f-8454-ef62c1b56fe1.png)

**Comment by lbroudoux** [comment]
Hi @FilipShavash,

Did you also change the redirect url within the `keycloak-realm/microcks-realm-sample.json`? I forgot to mention that in previous response but the line 90 should also be updated to the `http://<my_ec2_public_dns>:80/*` value so that Keycloak know that you should be redirected to this one after login.

**Comment by FilipShavash** [comment]
Indeed, redirect updated by running this command for each try and the same results:
jq '.applications |= map(if .name == "microcks-app-js" then .redirectUris = [ "EC2DNSHostName:8080/*" ] else . end) | .sslRequired |= "none"' keycloak-realm/microcks-realm-sample.json.bak > keycloak-realm/microcks-realm-sample.json

More and more i play around with this EC2 micro type instances it looks like machine is too weak to handle it. It becomes responsive only after restart, when dockers are down again.

**Comment by lbroudoux** [comment]
Hum... what type of instance have you? t2.micro?

**Comment by FilipShavash** [comment]
Exactly t2.micro.

This is the top -i after starting docker compose with 4 components:
![image](https://user-images.githubusercontent.com/45749969/129208322-eb4634a2-99e9-46f8-ab5d-7ec95607d84e.png)

And the instance become irresponsive the moment keycloak docker is fired up. As i said to run all 4 components first i have to remove all images with "docker-compose down --rmi all" and then spin up docker compose.  

This is the moment all 4 starts and then machine become unresponsive.

**Comment by FilipShavash** [comment]
I let this instance work for a while with the images being up and suddenly (after a night:)) it becomes responsive but still web page for microcks stays empty. But at least i was able to grab some logs from the containers.

Microcks:
![image](https://user-images.githubusercontent.com/45749969/129309236-35ea75ce-568c-4b29-8235-03a5a211eb3b.png)

Keycloak:
![image](https://user-images.githubusercontent.com/45749969/129309555-d5a05f7e-0763-4013-939a-04be93204650.png)

**Comment by lbroudoux** [comment]
Could you check the result of the "docker ps -a" command? We should see if there is 137 code error which spot a low memory situation.

**Comment by FilipShavash** [comment]
I had to restart instance again as it become inaccesible.

Stop and spin up containers and after that command docker ps -a:
![image](https://user-images.githubusercontent.com/45749969/129345477-079609df-6d7b-4ed1-956b-080b6c559948.png)

But again after a while it becomes inaccesible so cannot check memory usage.

**Comment by FilipShavash** [comment]
@lbroudoux I left EC2 micro being up for a couple of hours and this is what i see from "docker ps -a"
![image](https://user-images.githubusercontent.com/45749969/129527523-b6974bb2-cbf3-4403-a4b4-9b82bc39a932.png)

So i checked keycloak logs and quite a lot of "red" stuff is there, like:
![image](https://user-images.githubusercontent.com/45749969/129527757-2c3bdf4e-cc11-44ae-a83a-edb0b7a79e54.png)

![image](https://user-images.githubusercontent.com/45749969/129527910-c7ab050f-fd37-48e7-bcc3-5cf270826a27.png)

![image](https://user-images.githubusercontent.com/45749969/129527932-52cbfccc-1a4d-4495-b63c-e9dab7bba36b.png)

Some warnings too:
![image](https://user-images.githubusercontent.com/45749969/129528052-752c8fca-6a78-49ad-93c7-458338025868.png)


![image](https://user-images.githubusercontent.com/45749969/129528166-52b30431-d5eb-4ee8-804b-5e836470f78a.png)

So this freeze of server might be caused by the errors coming from keyclock. I just cannot figure out how to get rid of those.

**Comment by FilipShavash** [comment]
What about configuration file, mine seems not to have "keycloak.ssl-required=none". Maybe that is causing snow ball effect on the whole keycloak?

![image](https://user-images.githubusercontent.com/45749969/129529013-0c9fef86-3f70-4141-9a03-8698a71fad44.png)

**Comment by FilipShavash** [comment]
@lbroudoux attached full log from keycloak in case You would find some time to help me analyse that 

[keycloak.log](https://github.com/microcks/microcks/files/6990704/keycloak.log)

**Comment by lbroudoux** [comment]
> What about configuration file, mine seems not to have "keycloak.ssl-required=none". Maybe that is causing snow ball effect on the whole keycloak?
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/45749969/129529013-0c9fef86-3f70-4141-9a03-8698a71fad44.png)
> 
> 

ssl-required=none is inherited from the default application.properties file that is embedded into application. So you shouldn't have to redefine it.

**Comment by yada** [comment]
@FilipShavash @aj84276 and any other contributors are welcome to make this available 🙌
