### ISSUE TITLE
Test with a GET with URI_PARTS dispatcher result in a nullpointer exception

### ISSUE THREAD

**Issue by ChristianHauwert** [microcks/microcks#288]
Hi,

I am currently conducting a POC with Microcks (v1.0.0). It seems like a promising tool. :-) Nonetheless, I encountered an issue while using the native TEST feature of Microcks. :-(

Steps to reproduce:
-Importing a valid OAS file with 1 GET operation with exclusively 1 path variable (URI_PARTS ). OK
-Validating whether the mock works. It shows the response by copying the specified url in a browser. OK
-Testing the mock by using the inbuild TEST feature. By clicking NEW TEST, paste the copied url, selecting runner HTTP|POSTMAN and LAUNCH THE TEST.  NOK (see error message below)

Other dispatcher types seems to work though, where you use either query variable(s) or a combination of path and query variable(s). URI_PARAMS or URI_ELEMENTS 

Hope to hear from you soon?

Kind regards, Chris

[ERROR] io.github.microcks.service.TestRunnerService - Throwable while testing operation GET /v1/xxx/:yyy
java.lang.NullPointerException: null
        at io.github.microcks.util.test.HttpTestRunner.runTest(HttpTestRunner.java:160)
        at io.github.microcks.util.test.HttpTestRunner.runTest(HttpTestRunner.java:48)
        at io.github.microcks.service.TestRunnerService.launchTestsInternal(TestRunnerService.java:142)
        at io.github.microcks.service.TestRunnerService$$FastClassBySpringCGLIB$$e3e9c696.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:769)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:747)
        at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
        at org.springframework.aop.interceptor.AsyncExecutionAspectSupport.lambda$doSubmit$3(AsyncExecutionAspectSupport.java:276)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by lbroudoux** [comment]
Hi there!

Is your mock example defining a response header, at least Content-type? Seems like the runner is failing because it expecting a header at least.

Let me know if it helps,

**Comment by ChristianHauwert** [comment]
Thnx for your quick response.

That is exactly what I have used. 1 header with content-type json. 

Subsequently I managed to reproduce this same issue at the Pet Store example (as refered to in the documentation section) by deleting the query json segments and the refererence to it in the raw url (by hacking the collection json file). After a succesful import and validation of the dispatcher (changed from URI_ELEMENTS to URI_PARTS) the test fails with the exact same problem (a null pointer) while it was working when the query segments where still part of the collection... 

Note: the Pet-Shop example has even many headers (approx 10)...

Kind regards, Chris

**Comment by lbroudoux** [comment]
Ok. Thanks for quick response. Will have an in-depth look at it on tomorrow. It will be a shame to block your evaluation for this little glitch ;-)

**Comment by lbroudoux** [comment]
Hi @ChristianHauwert,

just check this issue and it seems to have been already fixed here: https://github.com/microcks/microcks/commit/da0c91a93ff521ebf1ab7c46966ad3c88b8c150a
I was not able to reproduce on my different installations.

If it's OK for you, I recommend moving to and evaluating the `1.1.0` release that is now available everywhere (container images, helm charts and operation) even if not yet announced. I had to write a little blog post first...

Let me know how things are going.

**Comment by ChristianHauwert** [comment]
Hi,

Thanks for looking into it on short notice! Appreciate it.

Good to hear that it already HD been resolved in the newer version. Lol. I suggested it to a colleague to update to the latest but we were to stubborn and also proud on our in depth analysis 🧐.

Will update Microck and let you know whether the issue is resolved!

Kind regards, Chris

**Comment by lbroudoux** [comment]
Thanks for great analysis indeed! Having the right stack trace and failure context always helps a lot.

**Comment by ChristianHauwert** [comment]
We have update Microcks to v1.1.0. Unfortunately it is not an improvement :-( and here is why:
We have used:
- The 'Pet-Store collection' with 2 operations (findbystatus & petId). 
-  our own service with exclusively 1 path variable

### **MOCKING (copying the url into a browser):**
**[Version 1.0.0]**
URI_PARAMS	     OK		PET	findByStatus	user_key && status	
URI_PARTS	     OK             our own service with exclusively 1 path variable
URI_ELEMENTS     OK		PET	petId		user_key

**[Version 1.1.0]**
URI_PARAMS	    OK		PET	findByStatus	user_key && status	
URI_PARTS	    NOK            our own service with exclusively 1 path variable
URI_ELEMENTS   NOK		PET	petId		user_key

With v1.1.0 we get even 404's in the browser with the specified examples (URI_PARTS & URI_ELEMENTS) where v1.0.0. all 3 types are supported correctly.

### **TESTING (using the in-build feature)**
**[Version 1.0.0]**
URI_PARAMS	     OK		PET	findByStatus	user_key && status	
URI_PARTS	     NOK           our own service with exclusively 1 path variable
URI_ELEMENTS     OK		PET	petId		user_key

**[Version 1.1.0]**
URI_PARAMS	    OK		PET	findByStatus	user_key && status	
URI_PARTS	    NOK             our own service with exclusively 1 path variable
URI_ELEMENTS   NOK		PET	petId		user_key

With v1.1.0 we get a 404 with the specified examples (URI_ELEMENTS) while this was working at version 1.0.0.

**Comment by lbroudoux** [comment]
Hi @ChristianHauwert,

In order to work in an efficient way on this, I have designed a new `DispatchTest` API that we could share to validate what is working and what is not working. Here's the link of the OpenAPI spec: https://gist.github.com/0388bd5cdafb6198bf4f5cf7e09456a5#file-dispatchertest-1-0-0-yaml

When I import this specification onto my installation, I have the following result with 3 operations. Each operation is using a different dispatcher type:

<img width="1292" alt="Capture d’écran 2020-10-29 à 17 10 28" src="https://user-images.githubusercontent.com/1538635/97601721-c3afb700-1a0a-11eb-8169-67ce00a22777.png">

I am able to invoke all the mocks correctly as shown by the curl commands below:

```sh
$ curl http://localhost:8080/rest/DispatcherTest/1.0.0/tests/foo
{"foo":"foo","bar":"foo","id":"foo"}%                                                                                                                                                                              
$ curl http://localhost:8080/rest/DispatcherTest/1.0.0/tests/bar
{"foo":"bar","bar":"bar","id":"bar"}% 
$ curl http://localhost:8080/rest/DispatcherTest/1.0.0/tests\?page\=0
[{"foo":"foo","bar":"foo","id":"foo"}]%
$ curl http://localhost:8080/rest/DispatcherTest/1.0.0/tests\?page\=1 
[{"foo":"bar","bar":"bar","id":"bar"}]% 
$ curl http://localhost:8080/rest/DispatcherTest/1.0.0/tests/foo/filter\?property\=foo
{"foo":"foo","id":"foo"}%
$ curl http://localhost:8080/rest/DispatcherTest/1.0.0/tests/bar/filter\?property\=bar
{"bar":"bar","id":"bar"}% 
```

When I'm launching a test using `HTTP` runner and pointing on Microcks own's mock URL, I got the following results:

<img width="1292" alt="Capture d’écran 2020-10-29 à 17 10 50" src="https://user-images.githubusercontent.com/1538635/97602406-8d266c00-1a0b-11eb-81e3-e9802d254de6.png">

with the same message payload as when using curl.

Would you mind trying with this OpenAPI so that we could share the same basis ?

Thanks,

**Comment by ChristianHauwert** [comment]
Thnx for suggesting this approach to analyze the issue. :-)

With both versions. v1.0.0 as well as v1.1.0 it is working fine (using your specfied yaml)! The mocking itself as well as the HTTP test execution.

However, when using the the PETSTORE example there is actually a difference. See: https://github.com/microcks/microcks.io/blob/master/content/documentation/getting-started.md#using-microcks
https://raw.githubusercontent.com/microcks/microcks/master/samples/PetstoreAPI-collection.json

One of the mocks is not working. Neither its corresponding test.
See:
[microcks-defects.docx](https://github.com/microcks/microcks/files/5466099/microcks-defects.docx)

Also, I dont understand why thet test (get-1) with an expected 404 is considered as a failure while the actual response is an actual 404.

Kind regards,

Chris

**Comment by lbroudoux** [comment]
Hi Chris,

Thanks for replaying this basic sample as we know now that basic stuffs are working well ;-) I suspect the Petstore collection being the culprit and maybe incomplete. This is one I wrote years ago and have not updated recently...

Anyway I will have a deep dive at it again during this week-end and let you know my findings. 

Thanks for your patience with your tests. I'll come back to you very soon. 

Kind regards,

**Comment by lbroudoux** [comment]
Hi Chris,

did some investigations and got an explanation on what's going wrong with the Petstore Collection.

It appears that while fixing an issue with encoding (see #261), we changed the way `resource paths` fragments are imported from Postman Collection.

With Microcks 1.0.0, a path specified as `/v2/pet/:petId/?user_key=...` in Postman Collection was imported as `/v2/pet/2`. When a request comes to the mocks endpoints this resource path is matched because equal to the one imported.

With Microcks 1.0.0, this path is now imported as `/v2/pet/2/` with trailing `/` and the matching with mock invocation cannot be done anymore.

So a quick workaround is to fix the Postman Collection as I did in https://github.com/microcks/microcks/commit/2bcb47d654bbb25c603e4946b5ad573e84d8fe71 . But a much more robust solution (consisting in cleaning any trailing `/`) should be provided during import process. I'll open a new issue to track that.

Now regarding the failing test with 404 exception. It appears that `HttpTestRunner` initial intent was not to do a full Http compliant test but to be much more used as a smoke test just to to check if an API endpoints have been deployed. Thus it does not compared received response code to expected one but just check it's in the 2xx range. So it behaves as expected even if:
* documentation should be more specific on that behavior,
* there's room for enhancements and maybe have the 2 tests polices : `SMOKE_TEST` and `HTTP_TEST`.
I'll have some thoughts at it and see if things can be adapted easily. I'd be happy to have your opinion on that point.

Best regards,

**Comment by lbroudoux** [comment]
Hi @ChristianHauwert,

Did you have the opportunity to have a look at above update?

Kind regards,

**Comment by ChristianHauwert** [comment]
Hi Laurent, 

First of all, I would like to thank you for you analysis and you spent time on it during the weekend. 👍

I don’t know what went wrong but I have commented on your last finding this afternoon. 

I was able to reproduce your solution by deleting the trailing slash. 😀

Therefore I think you can close this issue as soon as you opened the one where you want to track the code implementation for a clean import procedure...
 
Many thanks

Kind regards, Chris

**Comment by mrdasher** [comment]
Hi Laurant,

Together with Chris I am working on the same PoC for Microcks.
We indeed entered a reaction yesterday and I notice that a part of our reaction is missing.

Our reaction regarding to split up to 2 test policies is missing.
We think it is a wise idea to split the current HTTP_TEST into 2 policies you suggested.
The HTTP_TEST for functional testing and the SMOKE_TEST for checking the deployment.
When running the SMOKE_TEST the focus should only be to the 2xx range.

With kind regards,

Dennis

**Comment by lbroudoux** [comment]
Thanks @mrdasher for the feedback ! Much appreciated !

**Comment by ChristianHauwert** [comment]
Hi Laurent,

Thanks for the support so far! :-)

**Comment by lbroudoux** [comment]
No that #292 has been created, we can close this one.
