### ISSUE TITLE
Why are topic separators removed in MQTT producer?

### ISSUE THREAD

**Issue by 195858** [microcks/microcks#363]
Hi,

Microcks reformats the channel name in an Async API and generates a completely different topic to be used with MQTT.

All the topic levels are removed ( "/" replaced).
This changes the behaviour of the API completely as the subscriber side can not use wild cards in subscriptions.

Additionally a prefix is added.

All of this leads to incompatibility with a service generated from the "counter part" of the Async API specification as the Async API code gen templates typically don't do this kind of transformation.

The code for this is here - I'd lke to understand the rationale before I start modifying it in our forked repo
https://github.com/microcks/microcks/blob/63b54af4bf3ea67b9228cd55b24278fe1274d95d/minions/async/src/main/java/io/github/microcks/minion/async/producer/ProducerManager.java#L174

Thanks

**Comment by lbroudoux** [comment]
Hi, thanks for opening this issue ! 

Indeed this part of the code would deserve a big `@TODO` tag as we just address basic needs and topic syntax. This has clearly to be enhanced.

However there's a rationale for adding a prefix : Microcks is connected to 1 single broker for mocking and we need to avoid collisions between different APIs using same topic names or even different versions of the same API. That's why we're using this prefix.

Aside of this, the last part of the topic name should follow the full MQTT semantics. I think the replacement of `/` by `_` was just inherited from Kafka implementation...

**Comment by 195858** [comment]
> However there's a rationale for adding a prefix : Microcks is connected to 1 single broker for mocking and we need to avoid collisions between different APIs using same topic names or even different versions of the same API. That's why we're using this prefix.
> 
I'd argue information like this should be included in the channel names in the AsyncAPI - it should include an API namespace and version. Similar to REST/OpenAPI conventions.
In other words - this problem should be addressed by a well designed topic namespace. Otherwise you'd need to re-publish 

> Aside of this, the last part of the topic name should follow the full MQTT semantics. I think the replacement of `/` by `_` was just inherited from Kafka implementation...
OK, I'll fix this separately and send a pull request.

Thanks for the prompt reply!

**Comment by lbroudoux** [comment]
> I'd argue information like this should be included in the channel names in the AsyncAPI - it should include an API namespace and version. Similar to REST/OpenAPI conventions.
In other words - this problem should be addressed by a well designed topic namespace. Otherwise you'd need to re-publish

Agree that's in true for production and public communication purposes. However I do not see any other mean to avoid such collisions at development time... We applied the same mechanisms with REST mocks - adding a prefix to paths defined within OpenAPI contract.

Now tracked in #364 .
