### ISSUE TITLE
Increase the readiness probe time for OpenShift template

### ISSUE THREAD

**Issue by hguerrero** [microcks/microcks#39]
When deploying microcks is taking more than 100 seconds to start in my openshift cluster. If I don't remove or increase the time for the readiness probe the pod continues to crash all the time.

**Comment by lbroudoux** [comment]
Hi @hguerrero, when looking at my different environments, startup time of microcks pod is about 6 to 8 secs. The readiness probe is setup at 20 secs that seems very reasonnable. Have you checked that the extra delay you encounter cannot be due to a missing dependecy such as MongoDB not being ready because of no or very slow storage ?

**Comment by lbroudoux** [comment]
As we no longer provider OpenShift templates, this request is now out of scope. Moreover, we do not likely face probe timeout issues lately. So I'm closing this one and we could re-open another later if it comes that probes timeout should be updated in Helm or Operator.
