### ISSUE TITLE
Use expression language on test param/body Tests to use external values

### ISSUE THREAD

**Issue by jonathanvila** [microcks/microcks#391]
My use case is : 
1. send a POST to create an Entity, only sending 2 fields
2. response contains the ID
3. send a GET to retrieve the full Entity

Currently this sequence can not be tested and step 3 is always returning 404 therefore I can not test response integrity.

2 ways of solving this : 

1. introduce order in the tests , capture of values, use expression language in the params for the step 3 using the value of those captured values
2. we can do some curl executions before the Microcks test, and pass some values ( Ids ) as parameters to microcks, and then with expression language in the params/body request in Tests use them

**Comment by lbroudoux** [comment]
Hi @jonathanvila, thanks for raising this complex issue ;-)

At the origin - I would say "by design" - Microcks is not intended to solve this testing use-case that is much more related to behavior testing or persistent state testing. This testing use-case make assumptions of global behavior of a component and that behavior can also span multiple APIs / GUI / batch interactions. I would say that for this kind of problem, solutions like Cucumber or Selenium seems much more appropriated.

On its side, Microcks is focused on single interaction contract testing : validating that an interaction (a service invocation or API call) has been done as specified in a contract. It has no notion of *test order*, *operation dependencies* or this kind of thing. That's why I think it's a best practice to not tie together different examples / test scenarios of different API operations. You create an entity A, retrieve an entity B and remove an entity C. The reference dataset that you load in your database shall be of-course aligned with this and has B and C pre-populated.

But enough of theory ;-) I recognize that the testing scenario you describe is quite common and maybe it could be addressed in Microcks. In the past I was thinking of following ways to handle that :

1. Order the testing of an API operations according the HTTP verb : first `POST` operations, then `PUT` and `PATCH`, then `GET` and finally `DELETE` ones. This should cover roughly 80% of scenarios but does not allow complex orchestration with unpredictable entity ids for example,

2. Provide an explicit order number for operation. This could be implemented using the same mechanism as the one described in #311. Otherwise it could fallback to #1. This could cover X additional % of scenarios when 2 operations of the same verb have to be done in a specific order,

3. Ease external orchestration of operations tests. For that we would need to have the ability to filter operation(s) to launch as tests. It will allow more complex scenarios that may also involve versioning - e.g. write using a version `1.0` of the API and then read using another `2.0` version for example.

4. Finally as you describe : capture values of first operation(s) test(s) result and then providing some input parameters for subsequent operations tests. This would involve expression language enhancements as you suggest with external orchestration of tests.

So definitely a lot of work ;-) but that will lead the path to more sophisticated ways of doing tests in Microcks. My concern right now is does Microcks need to go that way ? Isn't there some risks trying to do a little bit of behavior testing or persistent state testing but not being as comprehensive nor easy to understand than a Selenium scenario ? 

What do you think about it ? I still think that contract testing is a different beast out here and is not correctly handled by above mentioned tools for example but is there a room for 2 different types of testing in your API CI/CD pipeline ? 

I would to header about pros/cons from the community !

**Comment by jonathanvila** [comment]
Hi Laurent.
I appreciate your thoughts.
I see the complexity on chainned tests, that's why I was proposing
something simple and decoupled.

I can make curl requests before the microcks tests. I only need to send
parameters from outside microcks into the microcks tests and then in every
test use an expression instead of a hard-coded value.

Now parameter is : applicationid=42 but it could be :
applicationid={{env.applicationid}}

Wdyt?

**Comment by lbroudoux** [comment]
Looks fine but I wanted to use this opportunity to discuss the whole story around tests and what could be envision for future. I see expression language as a part of the whole picture and wanted to share my views at the moment. 

Comments on them is more than welcomed!!
