### ISSUE TITLE
RBAC model for management segmentation / delegation

### ISSUE THREAD

**Issue by lbroudoux** [microcks/microcks#408]
The goal would be to implement RBAC within a Microcks instance in order to allow delegation of management on certain API mock definitions. Think of big organization having tens or hundred of API versions going over many different functional domains.

**Comment by romg66** [comment]
Hello @lbroudoux,

This feature is very interesting for the future of Microcks. We would like to mutualize Microcks across differents projects. Each project should be able to administrate it's own API and choose whether their API are visible to other projects.
This feature is mandatory for our company as we can't have one Microcks for each project. The RBAC model should answer our needs. In order to avoid mock's URL conflicts (because of same API name in different projects) it should maybe contains the domain name or id.

Thank you very much for your great work.
