### ISSUE TITLE
Private repositories support

### ISSUE THREAD

**Issue by nesl247** [microcks/microcks#48]
Is there no support for private repositories? Anytime I try to import a private repository or a file in one, there is no error. In the network tab of the console, I do see a 401 though.

I've not seen any way to authenticate myself.

**Comment by nmasse-itix** [comment]
Hi !

I do not know if it is supposed to work. Could you try by specifying the username and password in the url ? 

```
https://user:password@git.repo/path/to/repo
```

**Comment by lbroudoux** [comment]
Hi,

Authentication management for private repositories is not implemented right
now. However if your repos handles authentication in URL as proposed by
Nicolas, it should be ok.

Let us know for result but also for requirements regarding the feature so
that we will be able to plan support.

Thanks,

Le jeu. 26 juil. 2018 à 10:01, Nicolas MASSE <notifications@github.com> a
écrit :

**Comment by s-krawczyk** [comment]
+1 or way to upload it manually

**Comment by fleed** [comment]
This feature is really important in enterprises. I hope that it will get high priority

**Comment by lbroudoux** [comment]
Currently working on this one ;-) We should have something working within a week. Stay tuned !

**Comment by lbroudoux** [comment]
Hi @fleed, @s-krawczyk, @nmasse-itix and @nesl247 !

Support of Private repositories has now been added through the concept of `Secret`. Basically, and administrator admin will first create one or more `Secret` where will be stored authentication informations about a repository or sub-repository within organization (one per team for example).

Within a `Secret` you would be able to specify:
* `username` + `password` for a Basic Authentication / HTTP Authorization, 
* `token` for a Bear Authentication / HTTP Authorization,
* `token` + `tokenHeader` for a custom header-based Authentication / HTTP Authorization.

When using HTTPS to access your repository, `Secret` will also allow to associate a CA certificate using a PEM format. So that SSL Validation could also be turned on even for self-generated certificates.

Then when user declares a new `ImporterJob` he can specify which `Secret` should be used for accessing the repository. SSL Verification can also be turned off at the imported level.  

I've made a few tests using private GitLab or BitBucket repositories ; also using Gogs on a custom install with self-signed certificates ; also using LetsEncrypt certificates and everything seems fine. Hope you'll have some opportunities to also test and share your feedbacks.

**Comment by gsaslis** [comment]
Hi @lbroudoux ! 

is this functionality supported some other way when microcks is deployed outside of k8s/openshift?

**Comment by gsaslis** [comment]
@lbroudoux please ignore that last comment. As I hit the "Comment" button, it occurred to me that maybe the admin microcks user has access to some other functionality where they can define these `Secret`s, which is indeed the case. 

Sorry for the noise. :)

**Comment by lbroudoux** [comment]
No problem ! 
Even if they have the same name and serve the same purpose, `Secret`s in Microcks are local to Microcks and defined within Microcks by admin users.  So the feature is also supported when deployed outside of a Kubernetes cluster.
