### ISSUE TITLE
AsyncAPI documentation with 2.1.0 version is not supported 

### ISSUE THREAD

**Issue by jorgeromeral** [microcks/microcks#491]
Hi,

I have an issue when trying to view Async API documentation with the version 2.1.0 as seems to be incompatible despite the fact that in other aspects works properly. 
The error message: "Error: Version 2.1.0 is not supported."

![image](https://user-images.githubusercontent.com/61879583/134295230-3921f696-7886-4ae7-999f-0b9c02e81df1.png)

Microcks version: 1.3.0
Async API version: 2.1.0

Thanks for support!

**Comment by lbroudoux** [comment]
Hi @jorgeromeral 

Yes you're right, the AsyncAPI document generator supporting 2.1.0 was not yet released when 1.3.0 was launched. We updated it these last weeks and this issue is fixed in nightly builds. It should be available as part of the 1.4.0 in 2 weeks. If you want to check it out, you can install Microcks using the `latest` container image.

**Comment by jorgeromeral** [comment]
Ok, thanks for replying!!
