### ISSUE TITLE
Add a patternfly theme to UI

### ISSUE THREAD

**Issue by lbroudoux** [microcks/microcks#5]
Add Patternfly as an alternative/default UI so that we may have nice visual integration with some other tools like Keycloak or OpenShift

**Comment by lbroudoux** [comment]
Postponing this issue because it is much more than just offering a CSS alternative. Should be reconsidered while redesigning the whole GUI.

**Comment by lbroudoux** [comment]
New UX is now finished and merged into the `master` branch!

**Comment by dipak101505** [comment]
I'm eager to contribute to the microcks project. I've successfully established the local Spring Boot backend and MongoDB connection. However, I'm facing challenges while configuring the Angular application due to version incompatibilities within the package.json file. As I'm currently working on the 1.9.x branch, I'd appreciate guidance on resolving the conflicts and setting up Angular effectively.
