### ISSUE TITLE
docker compose instructions update

### ISSUE THREAD

**Issue by youngma0** [microcks/microcks#509]
The "improve this page" button here (https://microcks.io/documentation/getting-started-tests/) is a dead link.
I'll create an issue here instead.

It's entirely possible, even likely, that I don't know what I'm talking about but when running through the examples on the page above, I got stuck at this command.
```
docker run -i --rm -p 8282:8282 quay.io/microcks/quarkus-api-pastry:latest
```
I was able to connect to localhost:8282 from the browser but if I used that as the test endpoint, I got connection refused. I tried many different permutations with no luck. In the end I used this command instead and was able to get it to work using `pastry:8282 `as my test endpoint

```
docker run -i --name pastry --network=docker-compose_default --rm -p 8282:8282 quay.io/microcks/quarkus-api-pastry:latest
```

Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal

**Comment by lbroudoux** [comment]
Hey @youngma0 ! Thanks for raising this one.

> The "improve this page" button is a dead link.

Right. I fix the template to target the correct GitHub repository for quick edit and fix.

> I tried many different permutations with no luck.

Yep, this problem was a real pain as it changes with every docker version. I've updated the documentation to explain that `localhost` with work from your host but that now you have to use `host.docker.internal` from within the containers themselves. 

I also added your suggestion to make the `pastry` container join the docker-compose one as the final workaround.

It is now deployed at https://microcks.io/documentation/getting-started-tests/

Thanks again !
