### ISSUE TITLE
Mocks are disabled

### ISSUE THREAD

**Issue by LSzelecsenyi** [microcks/microcks#543]
Hi, I am trying to spin up the user signedup example api. Microcks is running, under the importer menu point I uploaded the UserSignedUpAPI-asyncapi.yml. When open the api details page under operations I see 'Mocks are disabled', and no messages are sent from the service. How can I enable mocking?

**Comment by lbroudoux** [comment]
Hi there ! 
Mocks may be disabled because of your install configuration. Have you enabled the `async` features? Have you a Kafka broker running and configured? In case you're using docker-compose, are you sure to use the correct compose file as stated [here](https://microcks.io/documentation/installing/docker-compose/#enabling-asynchronous-api-features)?

**Comment by LSzelecsenyi** [comment]
Thank you for your answer! `docker-compose -f docker-compose.yml -f docker-compose-async-addon.yml up -d` made the trick!
