### ISSUE TITLE
AMQP 0.9.1 / RabbitMQ AsyncAPI mocking/testing support

### ISSUE THREAD

**Issue by lbroudoux** [microcks/microcks#551]
As AMQP 0.9.1 is a valid [AsyncAPI Binding](https://github.com/asyncapi/bindings/tree/master/amqp), it may be a good candidate for integration within Microcks.

**Comment by lbroudoux** [comment]
No for the moment but 0.9.1 version support will be added for next 1.5.1 release. Help will be much appreciated for testing in coming weeks. Stay tuned !

**Comment by lbroudoux** [comment]
Hey @Hassen-BENNOUR
I've got something working on my side and will probably be able to push by the end of the week.
Could we sync in the forthcoming days to discuss how things are going ?

**Comment by Hassen-BENNOUR** [comment]
@lbroudoux 
 Thanks great!
 I'm currently making a small example to show how it works, with kafka.
 We can sync for sure yes

**Comment by lbroudoux** [comment]
Hey @eiki25 !
Mocking and testing support for AMQP / RabbitMQ is now available in `nightly` container images and `1.5.x` branch.

**Comment by lbroudoux** [comment]
Yes! We follow we AsyncAPI bindings specs for that. You can have a look at the samples I've used for tests during development here: https://github.com/microcks/api-lifecycle/blob/master/account-service-demo-amqp/account-service-asyncapi-1.2.0.yml#L9

For reference, here's the link to AsyncAPI AMQP binding specifications: https://github.com/asyncapi/bindings/tree/master/amqp

**Comment by Hassen-BENNOUR** [comment]
@eiki25 

You need to update your file [docker-compose/config/application.properties](https://github.com/microcks/microcks/blob/1.5.x/install/docker-compose/config/application.properties#L20) like below to update le supported-bindings :

```
# Explicitly telling the minion the protocols we want to support
#%docker-compose.minion.supported-bindings=KAFKA,WS

 %docker-compose.minion.supported-bindings=KAFKA,WS,AMQP

# %docker-compose.mqtt.server=localhost:1883
# %docker-compose.mqtt.username=microcks
# %docker-compose.mqtt.password=microcks

 %docker-compose.amqp.server=rabbitmq:5672
 %docker-compose.amqp.username=microcks
 %docker-compose.amqp.password=microcks
```

And run 
`microcks\install\docker-compose>docker-compose -f docker-compose.yml -f docker-compose-async-addon.yml -f kafdrop-addon.yml -f rabbitmq-addon.yml up -d`

**Comment by diedoman** [comment]
Hello @lbroudoux ! We've been trying to introduce microcks for testing our AMQP/RabbitMQ messages internally, but we are running into problems when trying to use routingKeys. Not sure if this issue is the place to report this though.

What we are trying to accomplish is as follows:

We have defined a channel (topic exchange), on which we are trying to push messages (with examples). The use-case of a topic exchange is routing by keys with delimiters (e.g. fruit.yellow, vegetable.green, *.blue). 

The problem is we cannot find a way to get the mocks to include a routing key. The examples being pushed by microcks are pushed to the topic exchange without an actual topic. The same is reproducible with the example mentioned here: https://github.com/microcks/api-lifecycle/blob/master/account-service-demo-amqp/account-service-asyncapi-1.2.0.yml#L9

The amqp-0-9-1 bindings from asyncapi mention the routingKey as being part of an operation:
```yaml
operations:
  userSignup:
    channel: 
      $ref: '#/channels/userSignup'
    bindings:
      amqp:
        expiration: 100000
        userId: guest
        cc: ['user.logs']
        priority: 10
        deliveryMode: 2
        mandatory: false
        bcc: ['external.audit']
        timestamp: true
        ack: false
        bindingVersion: 0.3.0
```

If I follow the implementation in the microcks repository I cannot find any function call of the amqpPublisher that sets the routing key to anything other than an empty string (e.g. https://github.com/microcks/microcks/blob/196a350e3d11c2245aea0ed1feec5fb15516cf90/minions/async/src/main/java/io/github/microcks/minion/async/producer/AMQPProducerManager.java#L121)

I think a workaround could be to use the queue type instead of routingKey, given that our 'API customer' also connect to the queue which consumes from the topic exchange. Main problem is that I expect that some of our API customers are actively using the routing key in the message, which would not be part of our test cases then.

Is this currently supported in some other way and/or perhaps something that is a good candidate for your roadmap? 

Please let me know if this should be reported as a separate issue and/or requires other information, more than happy to help out in whichever way possible ;)

**Comment by lbroudoux** [comment]
Can you please open a new issue for that? It will be easier to track. Thanks!
