### ISSUE TITLE
Improve podman-compose support

### ISSUE THREAD

**Issue by nmasse-itix** [microcks/microcks#568]
It would be nice to work on the podman-compose support to bring it on par with docker-compose support and reduce the maintenance burden.

Here are some ideas : 
- Use fully qualified container image names to prevent the user from choosing the wrong one
- Have only one template variant instead of two now (rootful + rootless)
- Investigate how we could have the same compose file for both docker-compose and podman-compose
- Use a different storage directory for rootless and rootful, in order to prevent file permissions errors when trying both modes in turn

**Comment by lbroudoux** [comment]
I've made some new tests yesterday with new versions of Podman (`podman version 4.5.1`) and Podman-compose (`podman-compose version: 1.0.6`) on my Mac M1 using than podman machine and things aren't brilliant ...

Didn't succeed making things work as there's an issue mounting the directory needed for MongoDB persistence in red-write mode. Here are my observations below:
* `/Users` seems now to be mounted by default in podman machine using virtio. `mount` command when ssh'ed in the machine gives the following line: `vol0 on /Users type 9p (rw,relatime,sync,dirsync,access=client,trans=virtio)`
* I had to allow write access to all to avoid `changing owner` issues at MongoDB startup. So do a `chmod 777 ./microcks-data`
* I also tried to put an additional `user: <uid>:<gid>` directive in compose file as I had to do it for Colima (see https://gist.github.com/lbroudoux/e167dcf046b9266781b61398e4256181). Otherwise MongoDB complains with read-only issues and does not succeed in writing any file. I retrieved <uid>:<gid> issuing the `podman machine ssh podman-machine-default id` command
* Once the above done, it succeeds in booting and writing some of its journal, WiredTiger, and lock files. However, it fails again with the following:
```
2023-06-07T13:17:18.381+0000 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=1390M,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),checkpoint=(wait=60,log_size=2GB),statistics_log=(wait=0),verbose=(recovery_progress),
2023-06-07T13:17:18.392+0000 E STORAGE  [initandlisten] WiredTiger error (1) [1686143838:392246][1:0xffff83bc7000], connection: /data/db/WiredTiger.wt: handle-open: open: Operation not permitted
2023-06-07T13:17:18.392+0000 I -        [initandlisten] Assertion: 28595:1: Operation not permitted src/mongo/db/storage/wiredtiger/wiredtiger_kv_engine.cpp 277
2023-06-07T13:17:18.393+0000 I STORAGE  [initandlisten] exception in initAndListen: 28595 1: Operation not permitted, terminating
```

Some complementary observations:
* On Mac, my directory flags are as follow with `staff` group having the id `20`:
```
drwxrwxrwx   2 laurent  staff    64B  7 jui 18:06 microcks-data
```
* On Podman machine, the directory flags are: 
```
drwxrwxrwx.  2 core games   64 Jun  7 18:06 microcks-data
```
with `games` having the group id `20` as well (checked this using `getent group games` command)
* On the container, the mounted directory flags (on /data/db) are:
```
drwxrwxrwx. 2 root    nogroup 64 Jun  7 16:06 db
```
with `nogroup` have the group id `65534`

**Comment by yada** [comment]
Regarding Linux, tested using Ubuntu 22.04.2 LTS with: 
```
$ podman-compose -v
podman-compose version: 1.0.6
['podman', '--version', '']
using podman version: 3.4.4
podman-compose version 1.0.6
podman --version
podman version 3.4.4
exit code: 0
```

I used Ubuntu packages available in the official repositories, so it is not the latest podman and podman-compose versions.

Using this yml file:
```
$ cat microcks-compose.yml
version: '2'

services:
  mongo:
    image: docker.io/library/mongo:3.4.23
    container_name: microcks-db
    volumes:
      - "~/tmp/microcks-data-podman:/data/db"
        #    user: "501:1000"

  postman:
    image: quay.io/microcks/microcks-postman-runtime:latest
    container_name: microcks-postman-runtime

  app:
    depends_on:
      - mongo
      - postman
    image: quay.io/microcks/microcks:nightly
    container_name: microcks
    volumes:
      - "./config:/deployments/config"
    ports:
      - "8080:8080"
      - "9090:9090"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATA_MONGODB_URI=mongodb://microcks-db:27017
      - SPRING_DATA_MONGODB_DATABASE=microcks
      - POSTMAN_RUNNER_URL=http://postman:3000
      - TEST_CALLBACK_URL=http://microcks:8080
      - SERVICES_UPDATE_INTERVAL=0 0 0/2 * * *
      - KEYCLOAK_ENABLED=false
      #- MAX_UPLOAD_FILE_SIZE=3MB
```

And it works as expected:
```
$ podman ps -a
CONTAINER ID  IMAGE                                             COMMAND      CREATED        STATUS            PORTS                                           NAMES
e55c04a64958  [docker.io/library/mongo:3.4.23](https://docker.io/library/mongo:3.4.23)                    mongod       5 minutes ago  Up 5 minutes ago                                                  microcks-db
52ebbe491216  [quay.io/microcks/microcks-postman-runtime:latest](https://quay.io/microcks/microcks-postman-runtime:latest)  node app.js  5 minutes ago  Up 5 minutes ago                                                  microcks-postman-runtime
6498d6a770a0  [quay.io/microcks/microcks:nightly](https://quay.io/microcks/microcks:nightly)                              5 minutes ago  Up 5 minutes ago  [0.0.0.0:8080](https://0.0.0.0:8080/)->8080/tcp, [0.0.0.0:9090](https://0.0.0.0:9090/)->9090/tcp  microcks

```

Please note, the changes in yml file:

1. Mongo image name prefix with "docker.io/library/" is mandatory to avoid this error:
```
podman_default --network-alias mongo mongo:3.4.23
Error: short-name "mongo:3.4.23" did not resolve to an alias and no unqualified-search registries are defined in "/etc/containers/registries.conf"
exit code: 125
```
Guess this should work for all distro and OS 👉 TBC to make it generic.

2. user line and trick for Mac `user: <uid>:<gid>` is commented and not necessary for Ubuntu/Linux.

PS: I will redo and keep you posted using the [Kubic project](https://build.opensuse.org/package/binaries/devel:kubic:libcontainers:unstable/podman/xUbuntu_22.04) packages for the latest  podman and podman-compose Ubuntu versions (though not as well-tested according to the https://podman.io/docs/installation).

**Comment by yada** [comment]
Same OS (Ubuntu 22.04) and same compose yaml file (see above) but using latest podman and podman-compose versions:
```
$ podman-compose -v
podman-compose version: 1.0.7
['podman', '--version', '']
using podman version: 4.5.1
podman-compose version 1.0.7
podman --version
podman version 4.5.1
exit code: 0
```

All passed and working as expected ✅

**Comment by lbroudoux** [comment]
Latest tests are now OK on Linux and MacOS. Closing this one !
