### ISSUE TITLE
[FEATURE] Add support to binding example and parameter value in event api (MQTT)

### ISSUE THREAD

**Issue by manuel-padovani** [microcks/microcks#600]
Hello, I tried to follow the instruction provided in REST API to bind in EVENT async api the channel parameter with a sample payload but its not working.

![image](https://user-images.githubusercontent.com/103757621/163580729-cc2fede6-f66c-4973-bb9a-8caf686613f8.png)

So I'm suppposing this is not suppoerted. I hope you can include this in next release.

Greetings.

**Comment by lbroudoux** [comment]
This is actually expected to already work... Will have a look and test at it soon.

**Comment by manuel-padovani** [comment]
Thank you very much, please let me know if I am wrong with something :)

**Comment by lbroudoux** [comment]
Ok I got it ... In fact, we had a sample that exists on that here: https://github.com/microcks/microcks/blob/master/webapp/src/test/resources/io/github/microcks/util/asyncapi/api-maintenance.async-api-spec-gh-master.yaml

However, this is a bit out of date as it was written before 2.1 of AsyncAPI was out and named examples for messages introduced. We let this part for later as at that time, AsyncAPI did not introduce examples for parameters but rather rely on a `location` field (see https://www.asyncapi.com/docs/specifications/v2.3.0#parameterObject).

So ideally, we'd have to rely on that field to for making it work post AsyncAPI 2.1 version. Will have to think about it a bit...

**Comment by manuel-padovani** [comment]
Ok, I understand. I hope it will be ready for the next one.

**Comment by lbroudoux** [comment]
Thanks. I'll try to put some priority on it. Would you be ready to help with tests?

**Comment by manuel-padovani** [comment]
Yes I've already a dev environment ready for this kind of purpose.
Let me know when it will be available and I will reserve some days to test it. 

:)

**Comment by lbroudoux** [comment]
Sorry for the long time before tackling this one again.... I had a look at it and it appear that the way to go is definitely to implement the `location` support as the construction you have on top remains invalid (`parameter` doesn't have an `examples` property, unfortunately - see [here](https://www.asyncapi.com/docs/reference/specification/v2.6.0#parameterObject)).

So I propose to mark this one as closed unsolved cause invalid and will tackle #846 as the next priority regarding AsyncAPI support. Sorry for ending things like this but I'll give a high priority to #846 so that your use-case could be solved the "official standard way" even if it requires a slight modification on your side.
