### ISSUE TITLE
Setup Microcks E2E as part of CI pipeline (no Jenkins Plugin)

### ISSUE THREAD

**Issue by yoadmike** [microcks/microcks#69]
Hi , 
Can you please suggest best practice for Microcks in CI .
Details on the CI pipeline step i would like to have:
1) Deploy Microcks into a newly created OpenShift Project - **Exist** 
2) Create "A" User for microcks to enable login later on from OC CLI - **let's assume it's generic and not microcks specific** 
3)  **The Important part**  - Setup an Import of Mock Projects from OC CLI.

**Comment by lbroudoux** [comment]
Hi @yoadmike,

not really sure to understand what you mean by "setup an import of mocks projects from OC CLI" ? Could you please elaborate ?

Also for me, Microcks is not the most adapted tool if your concerns and goals are to have "short-lived" mocks and mock infrastructure. Some other tools like Hoverfly will be really better for this.

Indeed, I started Microcks because when things are growing up and you want to apply mocking to many applications or at the whole organization level, we encounter new issues like :
* sharing design and mock definitions so that everyone use the same set of definitions for the same APIs,
* limiting the resources dedicated to mocking (if everybody is popping dedicated services for mocking, you could have *a lot* of resources *just* for mocking),
* dealing with tests of APIs implementations in a coherent way they were mocked,
* working on samples and data sets representativeness globally - for that, you’d like to involve architects or functional experts,
* managing not just the last API technology but also the legacy SOAP WebServices we usually build our new API on top, 
* keeping everything up-to-date, avoiding spending time refreshing definitions in different places.

So to me, Microcks is much more a tool that is always up - because if serves communication purposes and mocks can be used by any one and any time - and CI/CD pipelines may used it:
* from API/service consumer pipeline for mocking dependencies during tests,
* from API/service producer pipeline for triggering tests (goal of the Jenkins plugin).

Cheers,

**Comment by yoadmike** [comment]
Hi lbroudoux , as always thank you for the fast response , I appreciate the time you spent on reply. 

I'm pretty sure i was unclear so I'll simplfy the request .. while setup of microcks from cli you provide parameters (host, user/pass for several deployments) .. now on UI you have the option to create import job from git or to upload a postman or soapui project 

1st Option : [quicker setup] Can you add an option in microcks openshift install  to specify also the mock projects directory (with soapui project xmls , or postman  collection files)to be imported so it will happen in one shot and I will not need to do it from UI 
2nd Option : to provide a rest API that can be called externally to openshift to perform the import of project (again to remove the need to do that upload/import from UI)
3rd option : your suggestion 

The reason is that I have local CI and Master CI .. local CI have short life cycle till development of task is done and pushed to master , I need to setup microcks quick for that life cycle ..

What do you say , is it reasonable to have this ? I assumed that what ever that is done from UI can be done by Rest call or command line but couldn't find such option . I like microcks and would like to see it fly.

**Comment by nmasse-itix** [comment]
Hello @yoadmike,

There are REST APIs available. Part of the API calls are documented [here](http://microcks.github.io/contributing/api/) but the relevant steps for your use case are missing. 

For your use case, you would need to:
1) create a client in Keycloak (there is also an API for that)
2) get a token
3) create a job
4) activate the job
5) start the job

## 1. Create a client in Keycloak

Create a client as documented [here](https://www.keycloak.org/docs-api/3.0/rest-api/index.html#_clients_resource).

Key properties of this client :
- client_id: rest-client
- access type: confidential
- direct access grant enabled: false
- standard flow enabled: false
- implicit flow enabled: false
- service account enabled: true
- service account roles: 
  - admin

## 2. Authenticate with this new client and get a token

```sh
curl -s http://keycloak-microcks.app.openshift.test/auth/realms/microcks/protocol/openid-connect/token -d grant_type=client_credentials -d client_id=rest-client -d client_secret=REDACTED |jq -r .access_token |tee token
TOKEN="$(cat token)"
```

## 3. Create a job

```sh
curl -k -H "Authorization: Bearer $TOKEN" -XPOST -H "Content-Type: application/json" -d '{ "name": "TEST", "repositoryUrl": "https://raw.githubusercontent.com/nmasse-itix/rhte-api/master/postman_collection.json", "active": "true" }' http://microcks-microcks.app.openshift.test/api/jobs |jq -r .id |tee job-id
```

## 4. Activate the job

```sh
JOB_ID="$(cat job-id)"
curl -k -H "Authorization: Bearer $TOKEN" -XPUT http://microcks-microcks.app.openshift.test/api/jobs/$JOB_ID/activate
```

## 5. Start the job

```sh
JOB_ID="$(cat job-id)"
curl -k -H "Authorization: Bearer $TOKEN" -XPUT http://microcks-microcks.app.openshift.test/api/jobs/$JOB_ID/start
```

**Comment by yoadmike** [comment]
Thank you !!  possible to provide the REST API that Upload a "File" ? that will save a tones of time .
this is what i was missing and i didn't find doc for that ..

Till Now:  get Token , Gen User 

#!/bin/bash

echo "* Request for authorization"
RESULT=`curl --data "username=admin&password=admin&grant_type=password&client_id=admin-cli" http://<HOST>-<PORT>/auth/realms/master/protocol/openid-connect/token`

echo "\n"
echo "* Recovery of the token"
TOKEN=`echo $RESULT | sed 's/.*access_token":"//g' | sed 's/".*//g'`

echo "\n"
echo "* Display token"
echo $TOKEN

echo "\n"
echo " * user creation\n"
curl   http://<HOST>-<PORT>/auth/admin/realms/microcks/users -H "Authorization: bearer $TOKEN" -H "Content-Type: application/json"  --data '{"username":"testUser","enabled":true,"firstName":"testUser","lastName":"testUser","credentials":[{"type":"password","value":"Unix11!"}]}'

**Comment by nmasse-itix** [comment]
The API call would be :

```sh
curl -o /tmp/postman_collection.json https://raw.githubusercontent.com/microcks/api-lifecycle/master/beer-catalog-demo/api-contracts/Beer%20Catalog%20API.postman_collection.json
curl -k -H "Authorization: Bearer $TOKEN" -XPOST http://microcks-microcks.app.openshift.test/api/artifact/upload -F file=@/tmp/postman_collection.json
```

**Comment by yoadmike** [comment]
Yep , it was done and completed , all worked perfectly .

**Comment by lbroudoux** [comment]
Thanks for quick response. I'd be curious seing it in action ! Do you plan to write a blog post or something on what you set up ?

**Comment by lbroudoux** [comment]
If this is something you would be able to communicate on, it would be a great addition to the `Automation` part of the documentation ;-)

**Comment by yoadmike** [comment]
i'm not into blogging , but i can put here the idea + the Groovey Lib written for this .

**Comment by lbroudoux** [comment]
It would be great to share ! Many thanks !
