### ISSUE TITLE
Async API Microcks doesn't have the option to set a customised frequency apart from 3,10,30

### ISSUE THREAD

**Issue by kotaanudeep** [microcks/microcks#725]

**Comment by lbroudoux** [comment]
Hi there! Thanks for opening this issue. Could you add more details on that you'd actually need or require as options?

**Comment by kotaanudeep** [comment]
I am publishing the message to a kafka topic and the frequency i can set it through UI, from UI i am able to select only the values 3,10,30 seconds. But i want to publish the messages once in every 1 sec and even i want an option to customise the frequency as per my need and hence i am reaching out to you for the same.

**Comment by lbroudoux** [comment]
As of today, it is not possible to change frequencies using parameters in Helm or Operator installation. However I can guide you through the manual changes. How have you deployed Microcks?

**Comment by kotaanudeep** [comment]
Installed with docker compose but please provide me the way for Helm chart also.

**Comment by kotaanudeep** [comment]
@lbroudoux  request you to please provide the necessary information.

**Comment by lbroudoux** [comment]
Hey sorry... my attention was caught by some other tasks 😉 

So, when using docker-compose, you'll basically need to configure the 2 files found in `/config` sub-directory:  `application.properties` and `features.properties`. 

`application.properties` is used by the async minion component to know what are the frequencies to handle. You'll need to add a line like the one below because minion is using a config profile called `docker-compose`:
```
%docker-compose.minion.restricted-frequencies=1,3,10,30
```

`features.properties` is used by the UI to know which frequencies to propose in the select box. You'll need to add a line like the one below:
```
features.feature.async-api.frequencies=1,3,10,30
```

When installing Microcks using Helm chart or Operator, the operation basically the same but the 2 files are dispatched into 2 different `ConfigMap`.  `features.properties` is embedded in the `microcks-config` ConfigMap whereas `application.properties` is embedded into the `microcks-async-minion-config` ConfigMap.

In this setup, the async minion component is using a config profile named `kube` so you have to adapt the above line to something like:
```
%kube.minion.restricted-frequencies=1,3,10,30
```

Hope it helps!

**Comment by kotaanudeep** [comment]
Thanks a lot @lbroudoux it worked for me, Thanks for your support.
