### ISSUE TITLE
[AsyncAPI] Incorrect routing of mocked events for AMQP/RabbitMQ

### ISSUE THREAD

**Issue by pcuriel** [microcks/microcks#738]
Hello.

I think that mock events generated by Microcks for RabbitMQ are not properly routed.

If we take the [example document](https://github.com/microcks/api-lifecycle/blob/master/account-service-demo-amqp/account-service-asyncapi-1.2.0.yml) as reference, I would expect that the exchange to use is `signedup-exchange`, as defined by the channel binding.
```yaml
bindings:
      amqp:
        is: routingKey
        exchange:
          name: signedup-exchange
```

Likewise, the routing key to use, if I am not mistaken, should be the channel name, i.e. `user/signedup`.

However, after importing the example document into Microcks we can see that the exchange used is `AccountService-1.2.0-user/signedup`, a concatenation of the Document title, version and the channel name.
![image](https://user-images.githubusercontent.com/1854183/213418378-a0413032-dc20-4cad-9e88-e30a80b63d52.png)

And as far as I can see, no routing key (an empty one?) is used.

Am I doing something wrong? Or is this configurable somehow?

**Comment by lbroudoux** [comment]
Hey @pcuriel,

In order to avoid collisions with existing and application-reserved exchanges, we do not use the `exchange.name` information from spec but create and use our own exchange based on API name, version and channel. We use those elements to avoid collision with other APIs, other versions of the same API and channels - so that you can use a single broker for all APIs, versions and so on.

As of today we're using an empty routing key to simplify consumption of mock messages. Also if I understand it correctly the [AMQP Binding for AsyncAPI](https://github.com/asyncapi/bindings/tree/master/amqp) does not allow specifying a value for routing key...

Let me know if it makes sense for you or if you see some other options/behaviours that could be useful.

**Comment by pcuriel** [comment]
Hi @lbroudoux 

It makes sense to have the option to just not use the exchange.name, in order to prevent collisions. However, I think that it should:

- At least use the actual exchange.name.
  - That is: API name + version + exchange.name would make more sense to me.
- Be configurable. We should have the option to exclude API name + version and work with just the exchange.name.

IMHO, there are scenarios in which you need mock messages published in the real exchange (if you want to use microcks in an Integration Testing pipeline, for instance, the consumer should be ideally bound to the exchange defined in the AsyncAPI document).


Regarding the routing key issue, I think that in the context of RabbitMQ, the channel is supposed to be that.
Looking at [the channel definition in the spec](https://www.asyncapi.com/docs/concepts/channel):

> Users can define channels as a topic, queue, routing key, path, or subject depending on the protocol used.

So in the case of RabbitMQ I think routing key is the option [commonly assumed by the community](https://github.com/asyncapi/bindings/issues/44#issuecomment-768314616).

**Comment by lbroudoux** [comment]
This configuration option of excluding API name and version was also suggested in #3667 for the record.

As we didn't have the corresponding `topic name` in the first binding we supported (Kafka), we did consider the channel name for computing a destination name at that time and stuck with that convention. This can be surely updated but I have to look at other bindings to see if we can do something similar.

Thanks for the details on `routingKey`: I'll have to consider it.
