### ISSUE TITLE
Add standard Grafana dashboards for Microcks

### ISSUE THREAD

**Issue by lbroudoux** [microcks/microcks#871]
As all our components are instrumented and exports metrics in Prometheus format, we should produce some official Grafana dashboard for Microcks.

We see 2 different needs for this:
* Technical related: ensure the Microcks installation does not consume too many resources, degrade response time, or become irresponsive. A Grafana dashboard with time-series exploration would allow us to deep-dive into issues and establish correlation with different things. As Microcks is using Spring Boot Actuator internally, we may be able to reuse some typical/already existing Spring Boot dashboard elements,
* Business related: track some functional metrics of your Microcks instance. Questions we want to answer here are: what are the most used/unused mocks? what is the global trend of tests? what is the global trend of conformance metrics? what is the trend of conformance metric per domain? Or per service? ...

The first "Technical related" category shouldn't be an issue as we already export everything as Prometheus format on endpoints. 

The second "Business related" category may need some more adjustments as we just expose REST/JSON API endpoints for that and do not provide any deep and time-series oriented history. We would probably need to convert this instant metrics to Prometheus format using Micrometer or OpenTelemetry indicators stored in local registry. Still to be explored...

**Comment by siddharth-sable** [comment]
Hey @lbroudoux, I would love to work in this

**Comment by lbroudoux** [comment]
Sorry for the late reply, but I was traveling. It would be awesome if you could help for sure!
Maybe @alainphan has some getting started or best practices guides to share for bootstrapping this? Or if you have experience with Grafana, you may already have everything at hand...

**Comment by robertonav20** [comment]
Hi @lbroudoux,
from my opinion OpenTelemetry of course because this technology permit to export everything log/trace/metrics and redirect if need everywhere Prometheus/ElasticSearch/Jaeger ecc...

Regard to the metrics i suggest:

- number of call
- number of call by http code
- number of call by http url
- time of response
- number of tests
- number of success
- number of fail
- execution time

**Comment by alainpham** [comment]
Hello gents, 
I have been exploring the topic for last couple of days. The simplest path I can suggest to get all the observability signals leveraging the OTEL standard is to use the opentelemetry starter for Spring Boot 3.1+ provided by Grafana. 

Metrics logs and traces will be automatically labeled with similar values so that it provides seamless correlation afterwards.

I have played around with the micrometer framework that is part of native spring boot as well , but it currently only provides traces and metrics. Logs would need to be instrumented outside of the app which doesn't provide a good integration between all the signals. There are also many moving parts to configure and things don't seam to be very well documented.

I have documented everything in an examples here on a standard spring boot 3 app  + otel collector + loki +  prometheus, tempo +  grafana : 
https://github.com/alainpham/spring-boot-metrics-logs-traces-opentelemetry/tree/master

What I would suggest is now on microcks side to add custom counters into micrometer registry if you want to add specific mock related metrics. It will automatically be picked up by the otel instrumentation. If it's request counts I suggest you stick to the same naming conventions as the micrometer one and just add for example a label called mock_name to have the gra,ularity by mocks.

And actually if you want the least hassle we could also in the first version let the specific mock metrics been generated from the traces/spans by the tracing backend (I think the otel collector can do it as well).

**Comment by robertonav20** [comment]
Hi @alainpham
I'm agree with you just add a simple metric on inside micrometer registry and basic instrumentation of OTEL.

I've used grafana Loki on my raspberry with k3s And it's very small and easily to configure it.

Anyway for a very small environment I think is better to have some chart on microcks gui

**Comment by alainpham** [comment]
Gents, I have played around with the actual microcks code.  I have managed to configure things so that we get metrics on specific mock services.
This is the commit using grafana-opentelemetry-starter 
https://github.com/alainpham/microcks/commit/6f6a67559fe3589fc131ac243d1b6d7b91dacecd

Here are some screenshots using the existing Spring boot dashboard. Now we just need to tweak the dashboards to make it meaningful to Microcks.

![image](https://github.com/microcks/microcks/assets/13981031/a1ef260d-19f0-4ff6-ac93-d35b7aaef34e)

![image](https://github.com/microcks/microcks/assets/13981031/e2c19ffa-17d0-4714-9c77-4c7c6a7ae02c)

![image](https://github.com/microcks/microcks/assets/13981031/ed4342d9-0910-4111-8a00-21be69df1800)

**Comment by lbroudoux** [comment]
Hey @alainpham, this looks brilliant!

One question: shouldn't we open an issue related to "OpenTelemetry support (or migration from existing metrics system)" to allow a better separation of concern and tracking of changes? At first, I was thinking that it was just a matter of Grafana dashboard but the changes to come are more important. What do you think?

**Comment by lbroudoux** [comment]
Hey @alainpham!
I created #992 to track efforts on pure OpenTelemetry support addition. Thanks!
