### ISSUE TITLE
Unable to maintain test case execution order for an API.

### ISSUE THREAD

**Issue by KeerthigaMargesan4** [microcks/microcks#907]
### Reason/Context

unable to maintain test case execution order for an API.

### Description

Need to execute case 200 first and then case 423 & case 500 subsequently. Here, postman collection json data has the examples in order as 200, 423, 500 but after importing postman collection to microcks, order of the mock examples get changes for each APIs in microcks

### Implementation ideas

if any configuration available to specify the order of the example / test case execution would be great

**Comment by lbroudoux** [comment]
Hey there!

Thanks for opening this issue! This question has already been raised [here](https://github.com/microcks/microcks/issues/546) and [there](https://github.com/microcks/microcks/issues/391#issuecomment-825872050) but we never conclude it (unfortunately)...

As said in [the comments]((https://github.com/microcks/microcks/issues/391#issuecomment-825872050)), this is not Microcks intent to solve this "by design" but some workarounds or potential configuration flags have been mentioned in the past.

Please feel free to review pas discussion and share your thoughts if you'd like to help tackling this topic.

Cheers,

**Comment by KeerthigaMargesan4** [comment]
@lbroudoux , 
Thanks for your response. could you please provide the workarounds or potential configuration flags that you mentioned in the past.

**Comment by lbroudoux** [comment]
Hey there!

Currently, there's no implemented workaround: these were just thoughts on how we can do things. Previous discussions don't lead to final decisions on how to do things and what could be the next step.
What do you think of previously discussed options? (thinking of the 4 discussed in https://github.com/microcks/microcks/issues/391#issuecomment-825872050). Would you mind helping validating stuffs if we decide to go with an implementation?
