### ISSUE TITLE
Lightweight stack

### ISSUE THREAD

**Issue by robertonav20** [microcks/microcks#925]
### Reason/Context

Hi, 
in my case I have limited resources to mock and test my API so I ask to have microcks only with postman and without mongodb
Or if possible have only microcks single app

### Description

i would have a very lightweight microcks which only postman or without postman

### Implementation ideas

To support the first case without mongodb I suggest to use an alternative persistence layer like SQLite to store on filesystem
In docker environment a simple volume or inside kubernstes a persistent volume

For postman simple disable this feature in this configuration

**Comment by lbroudoux** [comment]
Hey @robertonav20!

This issue is actually addressed here: https://github.com/microcks/microcks/issues/851
Starting with version `1.8.0` (yet to be released in a few weeks), we provide a `uber` distribution that runs in a single container. 

You just have to find an available port on your machine (let's say `8585` hereafter) and run:
```sh
docker run -p 8585:8080 -it quay.io/microcks/microcks-uber:nightly
```

You have to use the `nigthly` tag at the moment before the release.

Hope it helps!
